## 读入语料，并进行清洗

In [1]:
#读取停用词
stopwords=[]
with open("E:/pythonwork/停用词.txt") as g:
    while True:
        line=g.readline()
        if line=="":
            break
        line=line.strip()
        stopwords.append(line)
print(stopwords)

In [2]:
##构建词袋
import re
wordbags=[]
with open("E:/pythonwork/199801_clear .txt") as f:
    file=f.read()
    word_= re.findall("([^a-zA-Z].*?)/",file) #匹配斜线前的词语
    for str in word_:
        str=str.strip()
        if (str not in stopwords) and len(str)!=19 and str!="":
            wordbags.append(str)
wordbags=list(set(wordbags))
print("词袋中的数量是: ",len(wordbags))
print(wordbags)

词袋中的数量是:  54033
['核电', '２２５．０３亿', '发财梦', '催缴', '公映', '低毒', '银色', '汇集', '官僚资本', '证', '圣但尼市', '沟通', '头功', '面人', '潜油', '续', '失足者', '密林', '牢记', '村子', '２∶０', '地方军', '小褂儿', '电缆桥', '１１８１２', '照明', '团圆', '安置', '磁共振', '两侧', '４１．１', '虚名', '石南', '八运', '神经中枢', '爱诗', '汽配', '谈笑', '拔河', '零点六九一六', '羊皮袄', '观点', '罗曼', '肿物', '笨', '激增', '倒行逆施', '肥西县', '尔均', '３８．６０', '塔里木', '回头客', '襄阳', '薄壳核桃', '神乎其神', '药械', '观望', '焕发', '一把', '生辉', '床铺', '道教', '平度市', '远科', '福斯特', '为官者', '如为', '餐饮', '８５．８万', '统计', '申办', '人才库', '庆链', '步调一致', '老工人', 'ＧＢ９２５４', '工本费', '１·１万', '男双', '偷税额', '恳望', '醒世', '烤红薯', '棱角', '少宇', '扫描术', '国桐', '烟客', '庆新', '销售税', '怒吼', '言谈', '围栏', '达夫', '建设者', '熙坤', '张掖', '高出一筹', '高屋建瓴', '钻石', '珠珠', '雷州', '乐仁', '拉·甘地', '热', '急迫', '乔迁之喜', '里道', '沂蒙', '在场', '漕河泾', '士华', '鹤壁市', '甩花手', '原籍', '矿工', '张贴者', '零点几', '兄弟', '抛光', '玉工', '富集', '是之', '疲惫', '萍踪浪迹', '绽开', '亚非拉', '知侠', '赐球', '６３７６', '恩情', '火车票', '中银', '增长额', '一见钟情', '２７５３．４亿', '空哥', '监场', '泛滥', '光彩', '克劳斯顿', '站址', '回到', '房龙', '赶排', '必武', '艰险', '青椒', '莎士比亚', 

In [3]:
len("19980101-01-001-001")

19

文本相似度计算方法有2个关键组件,即文本表示模型和相似度度量方法，

In [4]:
with open("E:/pythonwork/199801_clear .txt") as f:
    documents=f.readlines()
    documents_=[]
    for doc in documents:
        doc_= re.findall("([^a-zA-Z].*?)/",doc) #匹配斜线前的词语
        if(doc_):
            documents_.append(doc_)
    temp=[]
    documents_2=[]
    for i in range(len(documents_)-1):
        temp.extend(documents_[i])
        if(documents_[i][0][:-4]==documents_[i+1][0][:-4]):
            continue
        else:
            documents_2.append(temp)
            temp=[]      
print("拼接后文章数: %d 个 " %(len(documents_2)) )   

拼接后文章数: 3147 个 


In [5]:
documents_st=[]
for doc in documents_2:
    wordlist=[]
    for str in doc:
        str=str.strip()
        if (str not in stopwords) and len(str)!=19 and str!="":
            wordlist.append(str)
    documents_st.append(wordlist) 

In [320]:
documents_pri=[]
for doc in documents_2:
    s=""
    for i in doc:
        if(len(i)!=19):
            s=s+i.strip()
    documents_pri.append(s)   
# documents_pri[0]

In [6]:
len(documents_st)##处理后的标准格式的文档集

3147

In [7]:
print(documents_st[0])##查看第一篇文章格式

['迈向', '充满', '希望', '新', '世纪', '一九九八年', '新年', '讲话', '附', '图片', '张', '中共中央', '总书记', '国家', '主席', '江', '泽民', '一九九七年', '十二月', '三十一日', '１２月', '３１日', '中共中央', '总书记', '国家', '主席', '江', '泽民', '发表', '１９９８年', '新年', '讲话', '迈向', '充满', '希望', '新', '世纪', '新华社', '记者', '兰', '红光', '摄', '同胞', '朋友', '女士', '１９９８年', '来临', '之际', '中央', '广播', '电台', '中国', '国际', '广播', '电台', '中央', '电视台', '全国', '各族', '香港', '特别', '行政区', '同胞', '澳门', '台湾', '同胞', '海外', '侨胞', '世界', '各国', '朋友', '致以', '诚挚', '问候', '祝愿', '１９９７年', '中国', '发展', '历史', '平凡', '年', '中国', '决心', '继承', '邓', '小平', '同志', '遗志', '建设', '中国', '特色', '事业', '推向', '中国', '政府', '顺利', '恢复', '香港', '行使', '主权', '一国两制', '港人治港', '高度', '自治', '方针', '香港', '繁荣', '稳定', '中国', '共产党', '成功', '第十五', '次', '全国', '代表大会', '高举', '邓小平理论', '旗帜', '百年', '历史', '展望', '新', '世纪', '制定', '中国', '跨', '世纪', '发展', '纲领', '年', '中', '中国', '改革', '开放', '现代化', '建设', '向前', '迈进', '国民经济', '高', '增长', '低', '通胀', '发展', '态势', '农业', '生产', '收成', '企业', '改革', '深化', '生活', '进一步', '改善', '对外', '经济', '技术', '合作', '交流', '民主', '法制', '建设', 

## 生成词向量

### TF-IDF作为权重

#### 实现tf-idf（词频、最大词频标准化、文章长度标准化）

In [8]:
#tf-idf算法
##1.统计tf词频
def coutfreq(doc,num=0): #统计该文档内的词频 num参数可以选模式，默认0为普通词频，1为除以最大词频，2为除以文本长度
    worddict={}
    for word in doc:
        if word in worddict:
            worddict[word]+=1
        else:
            worddict[word]=1
    if(num==0):
        return worddict
    elif(num==1):
        maxtf= max(worddict.values())
        for k in worddict.keys():
            worddict[k]=(worddict[k]/maxtf)
        return worddict
    elif(num==2):
        for k in worddict.keys():
            worddict[k]=(worddict[k]/len(worddict))
        return worddict

In [131]:
%%time
# ##测试freq
# wd1=coutfreq(documents_st[0],1)
# print(wd1)
tflist_1=[]##标准化tf
tflist_0=[]##词频tf
tflist_2=[]##文章长度修正tf
for doc in documents_st:
    tflist_1.append(coutfreq(doc,1))
    tflist_2.append(coutfreq(doc,2))
    tflist_0.append(coutfreq(doc,0))

Wall time: 368 ms


In [93]:
import math
def countfreq_idf(wordbags,documents):
    dict_idf={}
    for word in wordbags:
        num=0
        for doc in documents:
            if word in doc:
                num+=1
        idf = math.log(len(documents)/(num+1))
        dict_idf[word]=idf
    return dict_idf

In [103]:
%%time
dict_idf=countfreq_idf(wordbags,documents_st)

Wall time: 8min 37s


In [104]:
dict_idf

{'核电': 5.856980319728187,
 '２２５．０３亿': 7.361057716504462,
 '发财梦': 7.361057716504462,
 '催缴': 7.361057716504462,
 '公映': 6.955592608396297,
 '低毒': 7.361057716504462,
 '银色': 6.667910535944516,
 '汇集': 5.569298247276406,
 '官僚资本': 6.955592608396297,
 '证': 5.6563096242660365,
 '圣但尼市': 7.361057716504462,
 '沟通': 4.498856835574993,
 '头功': 7.361057716504462,
 '面人': 7.361057716504462,
 '潜油': 7.361057716504462,
 '续': 6.444766984630307,
 '失足者': 7.361057716504462,
 '密林': 6.955592608396297,
 '牢记': 5.058472623510416,
 '村子': 5.6563096242660365,
 '２∶０': 6.444766984630307,
 '地方军': 7.361057716504462,
 '小褂儿': 7.361057716504462,
 '电缆桥': 7.361057716504462,
 '１１８１２': 7.361057716504462,
 '照明': 6.262445427836352,
 '团圆': 5.856980319728187,
 '安置': 4.293004781370844,
 '磁共振': 7.361057716504462,
 '两侧': 5.346154695962197,
 '４１．１': 7.361057716504462,
 '虚名': 6.444766984630307,
 '石南': 7.361057716504462,
 '八运': 7.361057716504462,
 '神经中枢': 7.361057716504462,
 '爱诗': 7.361057716504462,
 '汽配': 7.361057716504462,
 '谈笑': 7.361057

In [108]:
def countf_tf(word,dict):
    return dict[word]
def countf_idf(word,idict):
    return idict[word]

In [105]:
countf_idf("政府",dict_idf)

1.7682068025555422

In [14]:
countf_tf("政府",wd1)

0.08333333333333333

In [129]:
def count_tfidf(word,doc_index,tflist,dict_idf):
    '''word 查询词
       doc_index 查询文章在文档集中索引
       tflist_1f tf词频字典列表
       dict_idf idf字典
    '''
    dict_tf=tflist[doc_index]
    tf=dict_tf[word]
    idf=dict_idf[word]
    return tf*idf

In [130]:
##第一篇文章中标准化后前五十的关键词
d={}
for i in documents_st[0]:
     d[i]=count_tfidf(i,0,tflist_1,dict_idf)
d_order=sorted(d.items(),key=lambda x:x[1],reverse=True)
print(d_order[:50])

[('中国', 1.215799696217063), ('世纪', 0.7398860001749124), ('国际', 0.7211169028429748), ('各国', 0.6930868913233472), ('发展', 0.6829001640957153), ('和平', 0.616761395053676), ('澳门', 0.6095188833395576), ('台湾', 0.6038980163701821), ('世界', 0.5900235786645349), ('合作', 0.5826549487780065), ('两岸', 0.5337519078932682), ('同胞', 0.5202980748692225), ('经济', 0.5063212086835828), ('东盟', 0.471359135355503), ('充满', 0.43754100068298324), ('外交', 0.4311293388845394), ('友好', 0.41044003407484275), ('交流', 0.40125222632572694), ('迈向', 0.3996756965869104), ('方针', 0.3779708719589964), ('新年', 0.3708260702290029), ('一国两制', 0.3702739153683485), ('公正', 0.3680515614448351), ('希望', 0.3660452904301579), ('发展中国家', 0.3658869375778967), ('香港', 0.36406766757021836), ('建设', 0.36263684391402323), ('１２月', 0.36046511275328186), ('进一步', 0.3604267808731059), ('早日', 0.3558346052621788), ('开创', 0.3539618672745073), ('电台', 0.3521302917146093), ('３１日', 0.3503381079461957), ('新', 0.3481161908047018), ('改革', 0.32904528366146946), ('１９９８年'

In [132]:
##普通词频前五十的关键词
d={}
for i in documents_st[0]:
     d[i]=count_tfidf(i,0,tflist_0,dict_idf)
d_order=sorted(d.items(),key=lambda x:x[1],reverse=True)
print(d_order[:50])

[('中国', 29.17919270920951), ('世纪', 17.757264004197896), ('国际', 17.306805668231394), ('各国', 16.63408539176033), ('发展', 16.389603938297167), ('和平', 14.802273481288225), ('澳门', 14.628453200149384), ('台湾', 14.493552392884373), ('世界', 14.160565887948838), ('合作', 13.983718770672155), ('两岸', 12.810045789438437), ('同胞', 12.48715379686134), ('经济', 12.151709008405987), ('东盟', 11.312619248532073), ('充满', 10.500984016391598), ('外交', 10.347104133228946), ('友好', 9.850560817796225), ('交流', 9.630053431817446), ('迈向', 9.592216718085849), ('方针', 9.071300927015914), ('新年', 8.899825685496069), ('一国两制', 8.886573968840365), ('公正', 8.833237474676043), ('希望', 8.785086970323789), ('发展中国家', 8.781286501869522), ('香港', 8.73762402168524), ('建设', 8.703284253936557), ('１２月', 8.651162706078765), ('进一步', 8.650242740954543), ('早日', 8.540030526292291), ('开创', 8.495084814588175), ('电台', 8.451127001150624), ('３１日', 8.408114590708697), ('新', 8.354788579312842), ('改革', 7.897086807875267), ('１９９８年', 7.796651345120116), ('总书记

#### 利用gensim生成词向量

In [114]:
#利用gensim生成词向量
from gensim import corpora, similarities
dictionary = corpora.Dictionary([wordbags])
#TypeError: doc2bow expects an array of unicode tokens on input, 
# not a single string -->需要unicode编码，wordbags外面加【】变成list
dictionary.doc2bow(documents_st[0])
print(dictionary.token2id)
corpus = [dictionary.doc2bow(doc) for doc in documents_st]
print(len(corpus))

#### 利用scipy生成词向量

In [137]:
import numpy as np
import scipy
from scipy.sparse import coo_matrix ,csr_matrix
import sys
import time

In [172]:
def build_matrix(documents_st,tflist,dict_idf):
    matlist=[]
    for i in range(len(documents_st)):
        print("\r", end="")
        print("Process progress: {}%: ".format((i*100)/len(documents_st)), "▋" * (int)((i*100)/len(documents_st) // 2), end="")
        sys.stdout.flush()
        time.sleep(0.05)
        m=[count_tfidf(word,i,tflist,dict_idf) if word in documents_st[i] else 0 for word in wordbags]
        sp_mat=np.array(m)
        matlist.append(sp_mat)
    return matlist

In [173]:
%%time
mat_list=build_matrix(documents_st,tflist_1,dict_idf)

Download progress: 99.96822370511599%:  ▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋Wall time: 12min 1s


In [192]:
# 测试
print(np.where(sp_mat>0,1,0).sum())
print(len(set(documents_st[0])))

304
304


In [227]:
# 测试稀疏矩阵
from scipy.sparse import csr_matrix
row = np.array([0,2,2,0,1,2])
col = np.array([0,0,1,2,2,2])
data1 = np.array([1,2,3,4,5,6])
data2 = np.array([10,20,30,40,50,60])
X = csr_matrix((data1, (row, col)), shape=(3, 3))
Y = csr_matrix((data2, (row, col)), shape=(3, 3))
print(X.toarray())
print(Y.toarray())
print((csr_matrix.multiply(X,Y).toarray()))##这里的mutiply为点乘
print((csr_matrix.dot(X,Y)).toarray()) 

[[1 0 4]
 [0 0 5]
 [2 3 6]]
[[10  0 40]
 [ 0  0 50]
 [20 30 60]]
[[ 10   0 160]
 [  0   0 250]
 [ 40  90 360]]
[[ 90 120 280]
 [100 150 300]
 [140 180 590]]


In [236]:
csrlist=[]
for i in mat_list:
    coo = coo_matrix(i) ##稀疏矩阵转化为coo
    csr=coo.tocsr()#为了方便运算，转化为csr
    csrlist.append(csr)
print(len(csrlist))

3147


## 计算文本的相似度

### 余弦相似度

In [244]:
%%time
import pandas as pd
dict={}
for i in range(len(documents_st)):
    dict[i]=[0]*len(documents_st)
data=pd.DataFrame(dict,dtype='float')
dim=len(documents_st)
dotlist=[]
for i in range(len(documents_st)):
    dotlist.append(scipy.sqrt((csr_matrix.multiply(csrlist[i],csrlist[i])).sum()))

E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\

E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\

E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\

E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\

E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\

E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\

E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\

E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\

E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\

E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\

E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\

Wall time: 3.56 s


E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\lib\site-packages\ipykernel_launcher.py:9: DeprecationWarning: scipy.sqrt is deprecated and will be removed in SciPy 2.0.0, use numpy.lib.scimath.sqrt instead
  if __name__ == '__main__':
E:\python\

In [310]:
%%time
for i in range(dim):
    print("\r", end="")
    print("Process progress: {}%: ".format((i*100)/len(documents_st)), "▋" * (int)((i*100)/len(documents_st) // 2), end="")
    sys.stdout.flush()
    time.sleep(0.01)
    for j in range(dim):
        data[i][j]=csr_matrix.multiply(csrlist[i],csrlist[j]).sum()/(dotlist[i]*dotlist[j])

Process progress: 99.96822370511599%:  ▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋▋Wall time: 1h 9min 47s


In [311]:
data.head()

0         1         2         3         4         5         6     \
1     0.266844  1.000000  0.066927  0.060077  0.005150  0.238377  0.026339   
47    0.525525  0.462329  0.055546  0.071160  0.008736  0.229525  0.046846   
2960  0.544460  0.428053  0.060080  0.114017  0.018109  0.157164  0.037008   
426   0.258891  0.403633  0.043914  0.059283  0.005183  0.176630  0.051211   
1513  0.155869  0.361963  0.071511  0.059089  0.000636  0.177694  0.040554   

          7         8         9     ...       3137      3138      3139  \
1     0.032312  0.001578  0.118101  ...   0.013472  0.018287  0.007426   
47    0.040431  0.006851  0.213928  ...   0.003068  0.005663  0.010279   
2960  0.021104  0.009774  0.143538  ...   0.009058  0.033775  0.004742   
426   0.028558  0.002842  0.111166  ...   0.006795  0.008647  0.008563   
1513  0.053625  0.003141  0.086661  ...   0.007653  0.023712  0.006642   

          3140      3141      3142      3143      3144  3145  3146  
1     0.002936  0.007303  0.002444  0.000000  0.000000   0.0   0.0  
47    0.001268  0.008345  0.020379  0.002163  0.010261   0.0   0.0  
2960  0.002029  0.018363  0.023735  0.003462  0.016419   0.0   0.0  
426   0.000000  0.014014  0.010171  0.001109  0.006333   0.0   0.0  
1513  0.000962  0.005969  0.010072  0.000000  0.000000   0.0   0.0  

[5 rows x 3147 columns]

In [312]:
data.to_csv('cosdistancesimilarity.csv')

In [326]:
# name=[i for i in range(3147)]
# data.columns=name
data=data.sort_values(by=1,axis=0,ascending=False) ##对文章1相似度进行降序排序超出相似度最近的十篇文章
data.head(10)

0         1         2         3         4         5         6     \
1     0.266844  1.000000  0.066927  0.060077  0.005150  0.238377  0.026339   
47    0.525525  0.462329  0.055546  0.071160  0.008736  0.229525  0.046846   
2960  0.544460  0.428053  0.060080  0.114017  0.018109  0.157164  0.037008   
426   0.258891  0.403633  0.043914  0.059283  0.005183  0.176630  0.051211   
1513  0.155869  0.361963  0.071511  0.059089  0.000636  0.177694  0.040554   
1486  0.150434  0.356840  0.074322  0.045817  0.004398  0.134842  0.024112   
2932  0.123026  0.350582  0.016679  0.044050  0.000000  0.094725  0.013558   
2016  0.121654  0.344273  0.070750  0.097205  0.004611  0.151489  0.068919   
1677  0.125923  0.335426  0.049148  0.056349  0.006191  0.138598  0.042270   
1990  0.139990  0.318884  0.017974  0.024696  0.000000  0.106837  0.014736   

          7         8         9     ...       3137      3138      3139  \
1     0.032312  0.001578  0.118101  ...   0.013472  0.018287  0.007426   
47    0.040431  0.006851  0.213928  ...   0.003068  0.005663  0.010279   
2960  0.021104  0.009774  0.143538  ...   0.009058  0.033775  0.004742   
426   0.028558  0.002842  0.111166  ...   0.006795  0.008647  0.008563   
1513  0.053625  0.003141  0.086661  ...   0.007653  0.023712  0.006642   
1486  0.033921  0.003230  0.066263  ...   0.008246  0.001740  0.006968   
2932  0.012279  0.001609  0.038256  ...   0.006930  0.006286  0.005908   
2016  0.061607  0.005683  0.068324  ...   0.005262  0.006493  0.009458   
1677  0.037846  0.001932  0.058838  ...   0.004763  0.006278  0.001197   
1990  0.006971  0.000000  0.046354  ...   0.001833  0.001250  0.001705   

          3140      3141      3142      3143      3144  3145  3146  
1     0.002936  0.007303  0.002444  0.000000  0.000000   0.0   0.0  
47    0.001268  0.008345  0.020379  0.002163  0.010261   0.0   0.0  
2960  0.002029  0.018363  0.023735  0.003462  0.016419   0.0   0.0  
426   0.000000  0.014014  0.010171  0.001109  0.006333   0.0   0.0  
1513  0.000962  0.005969  0.010072  0.000000  0.000000   0.0   0.0  
1486  0.001629  0.007195  0.004417  0.000000  0.000000   0.0   0.0  
2932  0.000000  0.004308  0.008212  0.000000  0.002054   0.0   0.0  
2016  0.001253  0.008960  0.011211  0.000000  0.008299   0.0   0.0  
1677  0.000000  0.005303  0.003088  0.000000  0.000000   0.0   0.0  
1990  0.000000  0.004774  0.003754  0.000000  0.000000   0.0   0.0  

[10 rows x 3147 columns]

In [321]:
print(documents_pri[1])

在十五大精神指引下胜利前进——元旦献辞我们即将以丰收的喜悦送走牛年，以昂扬的斗志迎来虎年。我们伟大祖国在新的一年，将是充满生机、充满希望的一年。刚刚过去的一年，大气磅礴，波澜壮阔。在这一年，以江泽民同志为核心的党中央，继承邓小平同志的遗志，高举邓小平理论的伟大旗帜，领导全党和全国各族人民坚定不移地沿着建设有中国特色社会主义道路阔步前进，写下了改革开放和社会主义现代化建设的辉煌篇章。顺利地恢复对香港行使主权，胜利地召开党的第十五次全国代表大会———两件大事办得圆满成功。国民经济稳中求进，国家经济实力进一步增强，人民生活继续改善，对外经济技术交流日益扩大。在国际金融危机的风浪波及许多国家的情况下，我国保持了金融形势和整个经济形势的稳定发展。社会主义精神文明建设和民主法制建设取得新的成绩，各项社会事业全面进步。外交工作取得可喜的突破，我国的国际地位和国际威望进一步提高。实践使亿万人民对邓小平理论更加信仰，对以江泽民同志为核心的党中央更加信赖，对伟大祖国的光辉前景更加充满信心。１９９８年，是全面贯彻落实党的十五大提出的任务的第一年，各条战线改革和发展的任务都十分繁重，有许多深层次的矛盾和问题有待克服和解决，特别是国有企业改革已经进入攻坚阶段。我们必须进一步深入学习和掌握党的十五大精神，统揽全局，精心部署，狠抓落实，团结一致，艰苦奋斗，开拓前进，为夺取今年改革开放和社会主义现代化建设的新胜利而奋斗。今年是党的十一届三中全会召开２０周年，是我们党和国家实现伟大的历史转折、进入改革开放历史新时期的２０周年。在新的一年里，大力发扬十一届三中全会以来我们党所恢复的优良传统和在新的历史条件下形成的优良作风，对于完成好今年的各项任务具有十分重要的意义。我们要更好地坚持解放思想、实事求是的思想路线。解放思想、实事求是，是邓小平理论的精髓。实践证明，只有解放思想、实事求是，才能冲破各种不切合实际的或者过时的观念的束缚，真正做到尊重、认识和掌握客观规律，勇于突破，勇于创新，不断开创社会主义现代化建设的新局面。党的十五大是我们党解放思想、实事求是的新的里程碑。进一步认真学习和掌握十五大精神，解放思想、实事求是，我们的各项事业就能结出更加丰硕的成果。我们要更好地坚持以经济建设为中心。各项工作必须以经济建设为中心，是邓小平理论的基本观点，是党的基本路线的核心内容，近２０年来的实践证明，坚持这个中心，

In [322]:
print(documents_pri[47])

在全国政协新年茶话会上的讲话（一九九八年一月一日）（附图片１张）江泽民江泽民在茶话会上发表重要讲话。（新华社记者王新庆摄）同志们、朋友们：在这辞旧迎新的喜庆时刻，我代表中共中央、国务院、中央军委，向各民主党派、全国工商联和无党派爱国人士，向全国广大工人、农民、知识分子和干部，向人民解放军指战员、武警官兵、公安干警，向香港特别行政区同胞、澳门同胞、台湾同胞和海外侨胞，向关心和帮助中国现代化建设的国际友人，表示良好的祝愿！祝大家新年好！一九九七年，是我们党和国家历史上非常重要而又极不平凡的一年。年初，敬爱的邓小平同志离开了我们，全党全军全国各族人民紧密团结在党中央周围，毫不动摇地坚持党的基本理论和基本路线，把建设有中国特色社会主义事业继续推向前进。我国政府顺利恢复对香港行使主权，保持了香港的繁荣稳定，在完成祖国统一大业的道路上迈出了重要的一步。我们胜利召开党的十五大，高举邓小平理论伟大旗帜，总结历史，展望未来，制定了党在社会主义初级阶段的基本纲领，对改革开放和现代化建设跨世纪发展作出了全面部署。这两件大事，极大地鼓舞全党和全国各族人民更加紧密地团结起来，为把我国建成富强民主文明的社会主义现代化国家，完成祖国统一大业而奋斗。一九九七年，我国改革开放和现代化建设继续全面推进。国民经济实现了“高增长，低通胀”，主要经济指标基本达到宏观调控的预期目标，保持着良好的发展态势。农业生产再次获得好收成，企业改革继续深化，结构调整步伐加大，财政收入增长较快，金融形势稳定。城乡人民生活进一步改善。对外经济技术交流与合作继续扩大，国际收支状况良好。总的来看，去年的经济形势是好的，“九五”计划的良好开局得到巩固和发展。党的建设、民主法制建设和精神文明建设取得显著成就。人民解放军革命化、现代化、正规化建设得到进一步加强。我们伟大的祖国，保持社会政治、经济、文化协调发展和全面进步的兴盛局面。一九九七年，我国外交工作取得了重要成果。我国同周边国家的睦邻友好关系继续加强，同广大发展中国家的团结合作进一步巩固，同西方发达国家的关系得到改善和发展。通过高层互访，我国与美、俄、法、日等大国确立了面向二十一世纪发展双边关系的目标和指导方针。今天，我国已同南非共和国实现关系正常化，正式建立外交关系。我国还积极参与了区域性、洲际性经济贸易和技术合作与交流。我国的国际地位和国际影响进一步提高。国际舆论普遍认为，中

In [323]:
print(documents_pri[2960])

在春节团拜会上的讲话（附图片１张）李鹏（１９９８年１月２７日）李鹏总理在春节团拜会上讲话。（新华社记者兰红光摄）朋友们，同志们：五谷丰登的牛年即将过去，生机勃勃的虎年就要来临，全国人民沉浸在节日的喜悦之中。在这辞旧迎新之际，我们欢聚一堂，共庆传统的新春佳节。１９９７年是我国历史上非常重要而又极不平凡的一年。全国各族人民继承邓小平同志的遗志，把建设有中国特色的社会主义事业继续推向前进。香港顺利回到祖国怀抱，并保持繁荣稳定。这是中华民族的盛事，也是全世界瞩目的大事，中国人民为此感到无比自豪。中国共产党成功地召开了第十五次全国代表大会，高举邓小平理论伟大旗帜，总结百年历史，提出跨世纪的纲领，将指引着中国人民在社会主义现代化的大道上，不断夺取新的胜利。在过去的一年里，我国改革开放和各项建设取得新的成就。国民经济稳中求进，实现了高增长、低通胀，主要经济指标达到宏观调控的预期目标，保持着良好的发展态势。农业在连续几年丰收的基础上又获得好的收成。国有企业改革继续深化。经济结构调整步伐加快。重点工程建设进展顺利。对外经济技术交流日益扩大。在东南亚金融危机波及许多国家的情况下，我国保持了金融形势和整个经济形势的稳定。城乡市场丰富多彩，人民生活进一步改善。社会主义精神文明建设和民主法制建设取得新成绩，各项社会事业蓬勃发展。全国政通人和，民族团结，社会稳定，百业兴旺。各族人民对伟大祖国的美好未来充满信心和希望。１９９８年是全面贯彻落实党的十五大精神的第一年，也是实现了伟大历史转折的十一届三中全会召开２０周年。我们要坚持解放思想、实事求是的思想路线，继续推进经济体制和经济增长方式的根本转变，加强农业基础地位，加快以国有企业为重点的各项改革，加大经济结构调整力度，提高对外开放水平，促进国民经济持续快速健康发展。继续加强社会主义民主法制建设和精神文明建设，积极发展教育、科技、文化等各项事业，坚持不懈地开展反腐败斗争，巩固团结稳定的政治局面，促进社会全面进步。实现祖国的完全统一和民族振兴，是海峡两岸全体中国人的共同愿望。我们将一如既往，按照“和平统一、一国两制”的基本方针，努力发展两岸的广泛合作与交流。希望台湾当局以民族大义为重，采取实际行动，促进两岸直接通邮、通航、通商的早日实现，并尽早回应我们发出的在一个中国的原则下两岸进行谈判的郑重呼吁。当今世界多极化的格局日益明显。和平与发展仍然是时代的

In [47]:
# m=[count_tfidf(word,documents_st[0],documents_st,1) if word in documents_st[0] else 0 for word in wordbags]
# sp_mat=np.array(m)
# scipy.sqrt((csr_matrix.multiply(csrlist[],csrlist[i])).sum())

63.74074692514853